" Preamble {{{1
set nocompatible               "be iMproved, required
set backspace=indent,eol,start
let mapleader = ','

" VimPlug - Plugin Definitions {{{1

call plug#begin('~/.vim/plugged')
" Bundles here:

" File navigation
Plug 'junegunn/fzf', {'dir': '~/.fzf', 'do': './install --bin'} "Fuzzy search
Plug 'junegunn/fzf.vim'
Plug 'scrooloose/nerdtree' "Tree view

" Searching
Plug 'brooth/far.vim', {'branch': 'dev'} "Only dev branch has support for ripgrep
Plug 'jremmen/vim-ripgrep'

" Vim Motion Extensions
Plug 'tpope/vim-surround' "Easily change surrunding brackets
  Plug 'tpope/vim-repeat' "Repeat for vim-surround
Plug 'vim-scripts/argtextobj.vim' "Convert arguments into objects
Plug 'justinmk/vim-sneak' "Jump around buffer

" Vim manipulations
Plug 'godlygeek/tabular' "Easy tables
Plug 'scrooloose/nerdcommenter' "Easy Comments
Plug 'Raimondi/delimitMate' "Autocomplete brackets

" Vim Apparence
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
Plug 'kshenoy/vim-signature' "Show marks in the gutter
Plug 'Yggdroot/indentLine' "Show those indents BABY

" Syntax, Linters and Formaters
Plug 'sheerun/vim-polyglot' "Bunch of syntax in one plugin
Plug 'hail2u/vim-css3-syntax' "Extra CSS3 highlighting
Plug 'w0rp/ale' "Linter

" Git integration
Plug 'tpope/vim-fugitive' "Need to learn
  Plug 'tpope/vim-rhubarb' "Github plugins
Plug 'airblade/vim-gitgutter' "Show changes in gutter

" Auto Complete
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'zxqfl/tabnine-vim'

" Undo Tree
Plug 'mbbill/undotree'

" Vim QOL
Plug 'embear/vim-localvimrc' " Directory specific vimrc
Plug 'qpkorr/vim-bufkill' " Perserve window when deleting buffer
Plug 'vim-scripts/restore_view.vim' "Preserves folds through buffer enter and leaves
Plug 'wincent/terminus' "Better iterm integration
Plug 'yssl/QFEnter' "Open quickfix in last used pane

" Required:
call plug#end()

" Plugin Configs {{{1
" airline {{{2
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

let g:airline_left_alt_sep = ""
let g:airline_left_sep = ""
let g:airline_right_alt_sep = ""
let g:airline_right_sep = ""
let g:airline_symbols.branch = ""
let g:airline_symbols.readonly = ""
let g:airline_symbols.linenr = ""

let g:airline_section_x = airline#section#create_right(['tagbar', 'gutentags', 'grepper'])
let g:airline_section_y = ""
let g:airline_section_z = airline#section#create(['windowswap', 'obsession', '%l/%L:%3v'])

let g:airline#extensions#tabline#show_buffers = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamecollapse = 0
let g:airline#extensions#tabline#buffers_label = ''
let g:airline#extensions#tabline#right_sep = ''

let g:airline#extensions#ale#enabled = 1
let g:airline#extensions#ale#error_symbol = 'E:'
let g:airline#extensions#ale#warning_symbol = 'W:'

let g:airline#extensions#hunks#enabled = 0

" ale {{{2
let g:ale_lint_on_text_changed = 'never'
let g:ale_set_ballons = 1 "NVIM currently doesn't support hovers

let g:ale_linters = {
      \ 'javascript': ['eslint', 'flow'],
      \ 'ruby': ['rubocop']
      \}

nmap <silent> <leader>j :ALENext<CR>
nmap <silent> <leader>k :ALEPrevious<CR>

let g:ale_sign_error = '!'
let g:ale_sign_warning = '?'

" FLEXPORT
let g:ale_ruby_rubocop_options = '-c ~/flexport/.rubocop_next.yml --display-cop-names --display-style-guide'

" dash {{{2
nmap <leader>d <Plug>DashSearch

" delimitMate {{{2
let g:delimitMate_expand_cr = 1
let g:delimitMate_expand_space = 2

" far {{{2
let g:far#source='rg'
let g:far#highlight_match=0
let g:far#limit=10000
let g:far#result_preview=0
let g:far#preview_window_height=20
let g:far#preview_window_scroll_step=4

" Find and Replace (global)
nnoremap <leader>R :Far <c-r><c-w>  *<left><left>
vnoremap <leader>R "my:Far "<c-r>m"  *<left><left>

" fzf {{{2
" Jump to exsting window if possible
let g:fzf_buffers_jump = 1
let $FZF_DEFAULT_SORT = '100000'
let $FZF_DEFAULT_COMMAND = 'rg --files --no-ignore --no-messages --hidden --follow --glob "!.git/*"'

nnoremap <silent> <leader>pp :Files<CR>
nnoremap <silent> <leader>pb :Buffers<CR>

" localvimrc {{{2
let g:localvimrc_whitelist='.*/proj/\.lvimrc'

" nerdtree {{{2
nnoremap <silent> <leader>f :NERDTreeFind<CR>

" polyglot {{{2
let g:haskell_enable_quantification = 1   "to enable highlighting of `forall`
let g:haskell_enable_recursivedo = 1      "to enable highlighting of `mdo` and `rec`
let g:haskell_enable_arrowsyntax = 1      "to enable highlighting of `proc`
let g:haskell_enable_pattern_synonyms = 1 "to enable highlighting of `pattern`
let g:haskell_enable_typeroles = 1        "to enable highlighting of type roles
let g:haskell_enable_static_pointers = 1  "to enable highlighting of `static`
let g:haskell_backpack = 1                "to enable highlighting of backpack keywords

" ripgrep {{{2
" lets sort our results
let g:rg_binary = 'rg'
let g:rg_command = g:rg_binary . ' --vimgrep --sort path'

" gruvbox colour scheme {{{2
set termguicolors
let g:gruvbox_italic=1
let g:gruvbox_contrast_dark='hard'
let g:gruvbox_sign_column="bg0"

colorscheme gruvbox
set background=dark

" tabularize {{{2
nnoremap <leader>tt :Tabularize /

" undotree {{{2
nnoremap <leader>u :UndotreeToggle<CR>

" vim-sneak {{{2
let g:sneak#s_next = 1
let g:sneak#label = 1

map f <Plug>Sneak_s
map F <Plug>Sneak_S

" Coc {{{2
if !exists("CocLoadAllPlugins")
  function! CocLoadAllPlugins()
    CocInstall coc-emoji
    CocInstall coc-highlight
    CocInstall coc-lists
    CocInstall coc-tabnine
    CocInstall coc-yank

    CocInstall coc-css
    CocInstall coc-html
    CocInstall coc-json
    CocInstall coc-solargraph
    CocInstall coc-tsserver
  endfunction

  command! CocLoadAllPlugins :call CocLoadAllPlugins()
endif

" Don't give |ins-completion-menu| messages.
set shortmess+=c

" Requires mapping <cmd-p> to 0x10 in iterm
nnoremap <c-p> :CocList<CR>

" Remap keys for gotos
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

" Highlight symbol under cursor on CursorHold
autocmd CursorHold * silent call CocActionAsync('highlight')

" Remap for rename current word
nmap <leader>rn <Plug>(coc-rename)

" TODO: Look into `coc-format-selected`
" Use `:Fold` to fold current buffer
command! -nargs=? Fold :call     CocAction('fold', <f-args>)

" use `:OR` for organize import of current buffer
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

" vim-signature {{{2
nmap dmm m-
nmap dma m<space>

" indentLine {{{2
let g:indentLine_char = '|'
     
" NERDcommenter {{{2

" Disable default mappings
let g:NERDCreateDefaultMappings = 0

" Add spaces after comment delimiters by default
let g:NERDSpaceDelims = 1

" Insert comment delimiters on first column
let g:NERDDefaultAlign = 'start'

nmap <leader>cc <Plug>NERDCommenterToggle
vmap <leader>cc <Plug>NERDCommenterToggle

" gitgutter {{{2
set signcolumn=yes

let g:gitgutter_sign_deleted            = '▐'
let g:gitgutter_sign_added              = '▐'
let g:gitgutter_sign_modified           = '▐'
let g:gitgutter_sign_removed            = '▐'
let g:gitgutter_sign_removed_first_line = '▐'
let g:gitgutter_sign_modified_removed   = '▐'

" Vim Basic Settings {{{1

" Setting up persistent undo
if has("persistent_undo")
  let MyUndoDir='~/.undodir/'
  if !isdirectory(MyUndoDir)
    call system('mkdir -p ' . MyUndoDir)
  endif
  set undofile
  set undodir=~/.undodir/
endif

" Line Numbers
set number
set encoding=utf-8
set history=700
set showcmd

" Set autoindent
set autoindent

" Used for restore_view
set viewoptions=cursor,folds,slash,unix

" Highlights while searching
set incsearch
set hlsearch

" Turn off autofolding
"set nofoldenable

" Unix line endings
set ff=unix

" Displays Column Number
set ruler

" Commandline Height
set cmdheight=2

" Always show the status line
set laststatus=2

" Hides buffer when abandoned
set hidden

" Don't redraw while executing macros (good performance config)
set lazyredraw

" For regular expressions turn magic on
set magic

" No annoying sound on errors
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=
set tm=500

" Scroll with context
set scroll=3

" Tab settings
set expandtab
set shiftwidth=2
set softtabstop=-1 "Make it depend on shiftwidth
set tabstop=2

" Don't auto close all folds
set foldlevelstart=99

" Case insensitve if all lowercase. Else case sensitive.
set ignorecase
set smartcase

" Autocompletes filenames like bash
set wildmode=longest,list

" Shows unprintable characters
set list
set listchars=tab:▶·

" Prevent two file changes on save
set nobackup
set nowritebackup
" Enable faster updatetime
set noswapfile

" How long to wait before triggering CursorHold
set updatetime=50

set splitright

" Always have lines showing when scrolling
set scrolloff=5

if has("gui_running")
  set guioptions+=Tmrl
  set guioptions-=Tmrl
  if has("mac")
    set guifont=Menlo\ for\ Powerline:h12
    set guioptions+=r
  endif
endif

" Allow omni completion
set omnifunc=syntaxcomplete#Complete

" Allow modelines
set modeline

if executable('rg') == 1
  set grepprg=rg\ --vimgrep
end

" Display diffs vertically
set diffopt=vertical

" Custom Mappings {{{1
" Changes directory to current file TODO: Put this in shortcuts
nnoremap <leader>cd :cd %:p:h<CR>:pwd<CR>

" Don't move on *
nnoremap * *<c-o>

" Centers word in middle on n and N
nnoremap n nzzzv
nnoremap N Nzzzv

" Gotta put that space to good use
nnoremap <space> :bn<cr>
" Requires binding <s-space> to 0x00 in iterm
nnoremap <c-space> :bp<cr>

" Treat long lines as break lines
map j gj
map k gk

" Yanks from cursor to end of line.
map Y y$

" Quickly edit/reload the vimrc file
nnoremap <silent> <leader>ev :e $MYVIMRC<CR>
nnoremap <leader>lv :so $MYVIMRC<CR>

" Remove highlighting from searching
nnoremap <silent>\ :noh<CR>

" Allow quick window switching
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Re-highlight selection after shifting
vnoremap > >gv
vnoremap < <gv

" Shift key is too hard to press
vnoremap ; :
nnoremap ; :

" Commandline behaviour
nnoremap <c-a> <home>
nnoremap <c-e> <end>

inoremap <c-a> <home>
inoremap <c-e> <end>

cnoremap <c-a> <home>
cnoremap <c-e> <end>

" Faster movements
nnoremap s <c-d>
nnoremap S <c-u>

" Search (global)
nnoremap <leader>s :Rg <c-r><c-w>
vnoremap <leader>s "my:Rg "<c-r>m"

" Find and Replace (local)
nnoremap <leader>r :%s//gc<left><left><left>
vnoremap <leader>r "my:%s/<c-r>m//gc<left><left><left>

vnoremap / "my/<c-r>m<cr>

if has('nvim')
  " Terminfo problem
  " https://github.com/neovim/neovim/issues/2048#issuecomment-78045837
  " Current workaround
  nmap <BS> <C-w>h

  tnoremap <ESC> <C-\><C-n>

  tnoremap <A-h> <C-\><C-n><C-w>h
  tnoremap <A-j> <C-\><C-n><C-w>j
  tnoremap <A-k> <C-\><C-n><C-w>k
  tnoremap <A-l> <C-\><C-n><C-w>l
  nnoremap <A-h> <C-w>h
  nnoremap <A-j> <C-w>j
  nnoremap <A-k> <C-w>k
  nnoremap <A-l> <C-w>l
endif

" Commands {{{1

" Abbreviations for commandline
ca Wq wq

cnorea b BD
cnorea wb WBD

" User Defined Functions {{{1

command! EditAlias e ~/dotfiles/zsh/alias.zsh
command! OpenTerm call system("open -a iterm '".getcwd()."'")

"Autocmds {{{1
augroup blah
  autocmd!

  "Jump to last cursor position
  autocmd BufReadPost *
        \ if line("'\'") > 0 && line("'\'") <= line("$") |
        \    exe "normal g`\"" |
        \ endif

  " Turn off autoindent for comments for all files
  " :help |fo-table|
  autocmd FileType * setlocal formatoptions-=cro
  autocmd FileType html setlocal shiftwidth=2
  autocmd FileType sql setlocal shiftwidth=2
  autocmd FileType py setlocal shiftwidth=2
  autocmd Filetype jsx setlocal filetype=javascript,jsx

  autocmd BufNewFile,BufRead *.tex setfiletype tex
  autocmd BufNewFile,BufRead *.nvimrc setfiletype vim

augroup END

" Neovim {{{1
if has("nvim")
  " Faster startup
  let g:python_host_prog = expand('~') . '/.pyenv/versions/neovim2/bin/python'
  let g:python3_host_prog = expand('~') . '/.pyenv/versions/neovim3/bin/python'

  " Use the homebrew shell if it exists
  let brew_zsh = '/usr/local/bin/zsh'
  if !empty(glob(brew_zsh))
    " Vim takes the right side of the equal literally
    set shell=/usr/local/bin/zsh
  end

  augroup nvimGroup
    autocmd!
    " Don't display invisible characters
    autocmd TermOpen * setlocal nolist

    autocmd TermOpen * setlocal nonumber
  augroup END
endif
